### PR TITLE
new simple browser sample

### PR DESCRIPTION
**Pull request by whitetigle**
Hi, I'm currently writing the doc and I thought we'd need a simple minimal sample  with browser operations. So I created this browser sample.
It uses latest Fable.Borwser.Dom + Fable.Core.

### CODE REVIEW

**Comment by whitetigle** [comment]
I just added a simple browser sample with fetch + promises + json

**Comment by whitetigle** [comment]
added simple nodejs sample using fable-splitter

**Comment by whitetigle** [comment]
added nodejs add bundled with webpack.

**Comment by whitetigle** [comment]
added a simple sample using paket (because it's soooooo convenient)

**Comment by whitetigle** [comment]
Question: do you prefer I split the samples in different repos?

**Comment by MangelMaxime** [comment]
From my point of view, on the pros side having one sample per repo make it easier for people to use. Then can clone and directly use the project. While now they need to navigate between folders. Also, for tracking issue, it's easier to have one repo "specialized" in one example.

On the cons, having multiple repos make it a bit harder to maintain.

But my vote still goes to mono repo like it was in Fable 0.x / Fable 1.x. But I don't know @alfonsogarciacaro opinions on it.

**Comment by alfonsogarciacaro** [comment]
I think it may be also convenient for users to have different samples in the same repository. Thanks a lot @whitetigle!

**Pull request merged**
