### PR TITLE
Added mocha

### PR DESCRIPTION
**Pull request by whitetigle**
added simple sample featuring simple tests with mocha

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Aside: should we experiment with [ava](https://github.com/avajs/ava) instead? It comes with assertion and runs tests concurrently.

**Comment by whitetigle** [comment]
yes why not!

**Comment by whitetigle** [comment]
Do you have something or should I start from scratch?

**Comment by MangelMaxime** [comment]
There is https://github.com/YoloDev/Fable.Ava but I have no idea if this is up to date or no.

**Comment by alfonsogarciacaro** [comment]
No, I only [tried it with fable-splitter](https://github.com/fable-compiler/Fable/blob/6df66635fb33540de477e0720069d86893189844/src/fable-splitter/tests/index.js) but as you can see I didn't go beyond a few lines of JS 😸

**Comment by whitetigle** [comment]
Could please review the new interop sample before I merge and check if that's a proper way to do things? Thanks!

**Comment by whitetigle** [comment]
Ok just added a new sample: call Fable from JS. @MangelMaxime, @alfonsogarciacaro any other idea?

**Comment by alfonsogarciacaro** [comment]
Sorry @whitetigle, could you please merge/rebase this branch with master? It's including old commits and the diff is difficult to review.

**Comment by whitetigle** [comment]
done!

**Pull request merged**
